name: kernel_transformer
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Norbert <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  kernel: any
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
