name: widget_maker_2_0
description: Making widets

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.2.0"

dependencies:
  flutter:
    sdk: flutter

  uuid: ^2.0.1
  provider: ^2.0.1
  flutter_colorpicker: any
  code_builder: ^3.2.0
  dart_style: ^1.2.8
  #yaml: ^2.1.16
  rxdart: any
  file_system_explorer:
      git:
        url: https://github.com/Norbert515/file_system_explorer.git
  #flutter_desktop_widgets2:
  #  path: ../flutter_desktop_widgets2
  flutter_desktop_widgets2:
    git:
      url: https://github.com/Norbert515/flutter_desktop_widgets2.git
  flutter_highlight: ^0.6.0
  usage: 3.4.1
  flutter_hooks: ^0.7.0
  mustache:
    git:
      url: "https://github.com/Norbert515/mustache.git"

  ####################################################### WEB
  #flutter_web: any
####################################################### WEB

  # Widgets


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
####################################################### WEB
  #flutter_web_test: any

  ## ADD
  ## Add these dependencies to enable the Dart web build system
  #build_runner: ^1.2.2
  #build_web_compilers: ^1.1.0
####################################################### WEB

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: SourceCodePro
      fonts:
        - asset: assets/Source_Code_Pro/SourceCodePro-Regular.ttf
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages




dependency_overrides:
  yaml:
    git:
      url: https://github.com/Norbert515/yaml

####################################################### WEB

## ADD
## flutter_web packages are not published to pub.dartlang.org
## These overrides tell the package tools to get them from GitHub
#dependency_overrides:
#  flutter_web:
#    git:
#      url: https://github.com/flutter/flutter_web
#      path: packages/flutter_web
#  flutter_web_ui:
#    git:
#      url: https://github.com/flutter/flutter_web
#      path: packages/flutter_web_ui
#  flutter_web_test:
#    git:
#      url: https://github.com/flutter/flutter_web
#      path: packages/flutter_web_test


####################################################### WEB
